spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heydaze?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root0327
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false

logging:
  level:
    root: info
    page_110.app.messages.AuditingFilter: debug
    org.hibernate.SQL: debug # hibernate 를 이용한 sql 문을 출력 해준다